[package]
name = "seditor"
version = "0.1.0"
edition = "2024"
description = "S-expression editor"

[[bin]]
name = "sedit"
path = "src/main.rs"

[dependencies]
crossterm = { version = "0.29", features = ["bracketed-paste"] }
ratatui = { version = "0.30", features = ["unstable-rendered-line-info"] }
regex = "1"
